### ISSUE TITLE
Fix your CSS

### ISSUE THREAD

**Issue by Zipdox** [aeiou879/mppclone#2]
Why are there no semicolons on the last entry of each rule?

**Comment by aeiou879** [comment]
idk, I didn't make most of it

**Comment by ledlamp** [comment]
hmm, this wasn't the case with [brandon's original css](https://gitea.moe/lamp/m/src/branch/master/screen.css), must've been the idea of whatever was used to reformat; it's not invalid and it's not a problem to fix.

**Comment by aeiou879** [comment]
Fixed by @wolfy01 https://github.com/aeiou879/mppclone/commit/8ac5c9cfc548d33ce05f4299d5b50c4653e40704
